# 创建新账户
# elasticsearch-users useradd username
# 给账户授权
# elasticsearch-users roles -a superuser username
# elasticsearch-users roles -a kibana_system username
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    networks:
      - elastic-net
    environment:
      - ELASTIC_PASSWORD=changeme
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - "9200:9200"
#      - "9300:9300"
    volumes:
      - D:\es1\data:/usr/share/elasticsearch/data
#      - D:\es1\config:/usr/share/elasticsearch/config
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    networks:
      - elastic-net
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # Connect to Elasticsearch on port 9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Alternative way to specify Elasticsearch connection
      - ELASTICSEARCH_USERNAME=test
      - ELASTICSEARCH_PASSWORD=123456
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
#    volumes:
#      - D:\kibana1\config:/usr/share/kibana/config
networks:
  elastic-net: